# Multiple Linear Regression

In [1]:
# Importing libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

sns.set()
%matplotlib inline

In [2]:
# Importing dataset

dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset.head(8)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
5  26.27  59.44  1012.23  58.77  443.67
6  15.89  43.96  1014.02  75.24  467.35
7   9.48  44.71  1019.12  66.43  478.42

In [3]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### splitting the dataset into training set and test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Training the Multiple Linear Regression model on the Training set

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)
y_pred

array([431.42761597, 458.56124622, 462.75264705, ..., 469.51835895,
       442.41759454, 461.88279939])

In [13]:
model_predictions = y_pred.round(2)
model_predictions

array([431.43, 458.56, 462.75, ..., 469.52, 442.42, 461.88])

In [14]:
data = {'Actual Data':y_test, 'Predicted Data':model_predictions}
df = pd.DataFrame(data)
df

Actual Data  Predicted Data
0          431.23          431.43
1          460.01          458.56
2          461.14          462.75
3          445.90          448.60
4          451.29          457.87
...           ...             ...
1909       460.29          463.63
1910       452.42          457.04
1911       473.26          469.52
1912       438.00          442.42
1913       463.28          461.88

[1914 rows x 2 columns]

### Evaluating the Model Performance

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9325315554761303